<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <AssemblyName>probe</AssemblyName>
    <RootNamespace>probe</RootNamespace>
    <EnableDefaultCompileItems>true</EnableDefaultCompileItems>
    <RestorePackages>false</RestorePackages>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="tModLoader">
      <HintPath>e:\steam\steamapps\common\tModLoader\tModLoader.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>
</Project>
